-- CONSULTAS AVANÇADAS - SENSORES_FASE2

-- Distribuição do STATUS_IRRIGACAO (se a coluna existir)
SELECT STATUS_IRRIGACAO, COUNT(*) AS QTD
FROM SENSORES_FASE2
GROUP BY STATUS_IRRIGACAO
ORDER BY QTD DESC;

-- Médias por dia com filtragem de intervalo (ajuste as datas conforme necessário)
-- Exemplo: período do dashboard
SELECT
  TRUNC(DATA_COLETA)          AS DIA,
  ROUND(AVG(UMIDADE_SOLO),2)  AS AVG_UMID,
  ROUND(AVG(PH_SOLO),2)       AS AVG_PH,
  ROUND(AVG(FOSFORO_P),2)     AS AVG_P,
  ROUND(AVG(POTASSIO_K),2)    AS AVG_K
FROM SENSORES_FASE2
WHERE DATA_COLETA BETWEEN TO_DATE('2025-10-20','YYYY-MM-DD')
                      AND     TO_DATE('2025-10-29','YYYY-MM-DD')
GROUP BY TRUNC(DATA_COLETA)
ORDER BY DIA;

-- Leituras com maior temperatura e umidade (top 10)
SELECT *
FROM (
  SELECT *
  FROM SENSORES_FASE2
  ORDER BY TEMP_C DESC, UMIDADE_SOLO DESC
)
WHERE ROWNUM <= 10;

-- Registros com chuva > 0 ordenados por data (evidência de condição climática)
SELECT DATA_COLETA, HORA_COLETA, CHUVA_MM, TEMP_C, UMIDADE_SOLO, PH_SOLO
FROM SENSORES_FASE2
WHERE CHUVA_MM > 0
ORDER BY DATA_COLETA, HORA_COLETA;

-- (Opcional) Classificação simples via CASE quando não existir STATUS_IRRIGACAO
-- Ajuste limiares se desejar
SELECT
  DATA_COLETA,
  UMIDADE_SOLO,
  PH_SOLO,
  CHUVA_MM,
  TEMP_C,
  CASE
    WHEN UMIDADE_SOLO < 30 THEN 'IRRIGAR'
    WHEN UMIDADE_SOLO BETWEEN 30 AND 40 THEN 'IRRIGAR_LEVE'
    ELSE 'NAO_IRRIGAR'
  END AS SUGESTAO_REGRAS
FROM SENSORES_FASE2
ORDER BY DATA_COLETA;
